app/buyer/__init__.py
from flask import Blueprint

bp = Blueprint('buyer', __name__)

from app.buyer import routes

app/buyer/routes.py
from app.buyer import bp
from flask import render_template, request, make_response, jsonify, session, redirect, url_for
from app.utils.auth import login_required
from app.utils.auth import hash_password
import sqlite3
import random
from app import get_db


@bp.route('/')
@login_required
def index():
    parent_category = request.form.get('parent_category')

    if parent_category is None:
        db = get_db()
        db.row_factory = sqlite3.Row
        cursor = db.cursor()

        # status 0 is incomplete, 1 is complete - id must be passed as 1 element tuple
        cursor.execute("SELECT * FROM categories WHERE parent_category = 'Root'")
        rows = cursor.fetchall()
        db.close()

        # return render_template('standin_name/some_page.html', result=rows)

        # this return is just for testing with test script
        result = [dict(row) for row in rows]
        return render_template('buyer/index.html', result=result)

    return render_template("buyer/index.html")


@bp.route('/search', methods=['POST'])
def search():
    search_val = request.form.get('search')
    search_val_query = "%" + search_val + "%"
    min_cost_range = request.form.get('minCostRange')
    max_cost_range = request.form.get('maxCostRange')

    # If nothing was entered, search returns no products
    if search_val is "":
        return render_template('buyer/search.html', search=search_val, result=None)

    db = get_db()
    cursor = db.cursor()

    try:
        rows = cursor.execute("""SELECT *
                                 from Product_Listings
                                 join Sellers
                                 on seller_email = email
                                 where ((category LIKE ?) or (product_title LIKE ?) or (product_description LIKE ?) or (business_name = ?)) and (product_price >= ? and product_price <= ?) and (quantity != 0)
                              """,(search_val_query, search_val_query, search_val_query, search_val_query, min_cost_range, max_cost_range)).fetchall()
    except Exception as e:
        print(e)
        return f'Error: {e}'
    finally:
        db.close()

    result = [dict(row) for row in rows]
    return render_template('buyer/search.html', search=search_val, results=result)

@bp.route('/get_sub_cat', methods=['POST'])
def get_sub_cat():
    req = request.get_json()
    parent_category = req['parent']

    db = get_db()
    db.row_factory = sqlite3.Row
    cursor = db.cursor()

    # status 0 is incomplete, 1 is complete - id must be passed as 1 element tuple
    cursor.execute("SELECT * FROM categories WHERE parent_category = ?", (parent_category,))
    rows = cursor.fetchall()
    db.close()

    result = [dict(row) for row in rows]
    #print(result)

    res = make_response(jsonify(result), 200)

    return res

@bp.route('get_setting')
def get_setting():
    user = session.get('user')

    db = get_db()
    db.row_factory = sqlite3.Row
    cursor = db.cursor()

    cursor.execute("""SELECT BUYERS.email, BUYERS.business_name,
                        CREDIT_CARDS.credit_card_num, CREDIT_CARDS.card_type, CREDIT_CARDS.expire_month, CREDIT_CARDS.expire_year, CREDIT_CARDS.security_code,
                        ADDRESS.address_id, ADDRESS.zipcode, ADDRESS.street_num, ADDRESS.street_name from Buyers
                        JOIN USERS on Buyers.email = USERS.email
                        JOIN Credit_Cards on Buyers.email = Credit_Cards.owner_email
                        JOIN ADDRESS on Buyers.buyer_address_id = ADDRESS.address_id
                        WHERE BUYERS.email = ?""", (user,))
    rows = cursor.fetchall()
    db.close()

    ret = [dict(row) for row in rows]

    #print(ret)
    return render_template('buyer/setting.html', result=ret)

@bp.route('update_setting', methods=["POST"])
def update_setting():
    user = session.get('user')
    business_name = request.form.get('business_name')
    credit_card_num = request.form.get('credit_num')
    expire_date = request.form.get('expire_date')
    expire_date_parse = expire_date.split('/')
    security_code = request.form.get('security_code')
    zipcode = request.form.get('zip_code')
    street_name = request.form.get('street_name')
    street_num = request.form.get('street_num')
    address_id = request.form.get('address_id')
    password = request.form.get('password')
    conf_password = request.form.get('conf_password')

    db = get_db()
    db.row_factory = sqlite3.Row
    cursor = db.cursor()

    #cursor.execute("UPDATE Sellers set balance = balance + ? where email = ?", [price, seller_email])
    cursor.execute("UPDATE BUYERS SET business_name = ? where email = ?",
                   [business_name, user])

    cursor.execute("UPDATE Credit_Cards SET credit_card_num = ? where owner_email = ?",
                   [credit_card_num, user])
    cursor.execute("UPDATE Credit_Cards SET expire_month = ? where owner_email = ?",
                   [int(expire_date_parse[0]), user])
    cursor.execute("UPDATE Credit_Cards SET expire_year = ? where owner_email = ?",
                   [int(expire_date_parse[1]), user])
    cursor.execute("UPDATE Credit_Cards SET security_code = ? where owner_email = ?",
                   [security_code, user])

    cursor.execute("UPDATE Address SET zipcode = ? where address_id = ?",
                   [int(zipcode), address_id])
    cursor.execute("UPDATE Address SET street_name = ? where address_id = ?",
                   [street_name, address_id])
    cursor.execute("UPDATE Address SET street_num = ? where address_id = ?",
                   [int(street_num), address_id])
    db.commit()

    if password == conf_password:
        password = hash_password(password)
        cursor.execute("UPDATE USERS SET password = ? where email = ?",
                       [password, user])
        db.commit()
        db.close()
    else:
        db.close()
        return redirect(url_for('buyer.get_setting'))

    return redirect(url_for('buyer.get_setting'))

@bp.route('update_email', methods=["POST"])
def update_email():
    new_email = request.form.get('new_email')
    user = session.get('user')

    db = get_db()
    db.row_factory = sqlite3.Row
    cursor = db.cursor()

    cursor.execute("INSERT INTO Requests (request_id, sender_email, helpdesk_staff_email, request_type, request_desc, request_status) VALUES (?, ?, ?, ?, ?, ?)",
                   [random.randint(1, 100000000), user, 'helpdeskteam@nittybiz.com', 'ChangeID', 'Please change my ID to ' + new_email, 0])
    db.commit()

    user = session.get('user')

    db = get_db()
    db.row_factory = sqlite3.Row
    cursor = db.cursor()

    cursor.execute("""SELECT BUYERS.email, BUYERS.business_name,
                            CREDIT_CARDS.credit_card_num, CREDIT_CARDS.card_type, CREDIT_CARDS.expire_month, CREDIT_CARDS.expire_year, CREDIT_CARDS.security_code,
                            ADDRESS.address_id, ADDRESS.zipcode, ADDRESS.street_num, ADDRESS.street_name from Buyers
                            JOIN USERS on Buyers.email = USERS.email
                            JOIN Credit_Cards on Buyers.email = Credit_Cards.owner_email
                            JOIN ADDRESS on Buyers.buyer_address_id = ADDRESS.address_id
                            WHERE BUYERS.email = ?""", (user,))
    rows = cursor.fetchall()

    db.close()
    #return redirect(url_for('buyer.get_setting', ticket_created = 'true'))

    ret = [dict(row) for row in rows]

    return render_template('buyer/setting.html', result=ret, ticket_created = 'true')

app/templates/buyer/index.html
{% extends 'base.html' %}

{% block style %}
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/buyer.css') }}">
{% endblock %}

{% block navbar_content %}
    <li class="nav-item active">
        <a class="nav-link" href="{{ url_for("buyer.index") }}">Home <span class="sr-only">(current)</span></a>
    </li>
    <li class="nav-item active">
        <a class="nav-link" href="{{ url_for("buyer.get_setting") }}">Setting <span class="sr-only">(current)</span></a>
    </li>
    <li class="nav-item active">
        <form action="{{ url_for('api.logout') }}" method="POST">
            <button type="submit" class="nav-link btn btn-link active" style="font-size: 17.6px;">Logout</button>
        </form>
    </li>
    <li class="nav-item active">
        <form class="form-inline" method="POST" action="{{ url_for("buyer.search") }}">
            <input class="form-control search-field" type="search" placeholder="Search for Product" aria-label="Search" name="search" id="search">
            <button class="btn btn-light my-2 my-sm-0" type="submit">Search</button>
            <input type="hidden" value="0" id="minCostRange" name="minCostRange">
            <input type="hidden" value="1000000" id="maxCostRange" name="maxCostRange">
        </form>
    </li>
{% endblock %}

{% block main_content %}
    <!--<form method="post" action="{{ url_for("api.prod_by_cat") }}">
        <label for="category"></label>
        <input id="category" name="category">
        <input type="submit" value="test submit">
    </form>-->
    <div class="page-container">
        <div class="cat-hierarchy-container">
            <h2>Categories</h2>
            {% for i in result %}
                <div class="category-container">
                    <form method="post" action="{{ url_for("api.prod_by_cat") }}">
                        <input type="hidden" value="{{ i.category_name }}" name="category" id="category">
                        <input type="submit" value="{{ i.category_name }}" class="cat-button">
                    </form>
                    <button onclick="get_sub_category('{{ i.category_name }}');swap('{{ i.category_name }}')" class="btn" type="button" data-toggle="collapse" data-target="#{{ i.category_name }}"
                            aria-expanded="false" aria-controls="{{ i.category_name }}" id="{{ i.category_name }} expand">
                        +
                    </button>
                </div>
                <div class="collapse" id="{{ i.category_name }}" style="margin:0 0 0 30px"></div>
            {% endfor %}
        </div>
    </div>
    <script>
        function swap(category) {
            var button = document.getElementById(category + " expand");
            if (button.innerHTML === "-") {
                button.innerHTML = "+"
            } else {
                button.innerHTML = "-"
            }
        }
        function get_sub_category(category) {
            var isEmpty = document.getElementById(category).innerHTML === "";
            var subCatDiv = document.getElementById(category);
            if (isEmpty === true) {
                var parent_cat = {
                    parent: category
                }

                fetch(`${window.origin}/buyer/get_sub_cat`, {
                    method: "POST",
                    credentials: "include",
                    body: JSON.stringify(parent_cat),
                    cache: "no-cache",
                    headers: new Headers({
                        "content-type": "application/json"
                    })
                })
                .then(function (response) {
                    if  (response.status !== 200) {
                        console.log(`Response status was not 200: ${response.status}`)
                    }

                    response.json().then(function (data) {
                        for (const key in data) {
                            if (data.hasOwnProperty(key)) {
                                const newDiv = document.createElement("div");
                                newDiv.className = "category-container";

                                const newForm = document.createElement("FORM");
                                newForm.method = "post";
                                newForm.action = "{{ url_for("api.prod_by_cat") }}";
                                newDiv.appendChild(newForm);

                                const catName = document.createElement("input");
                                catName.type = "hidden";
                                catName.value = data[key].category_name;
                                catName.name = "category";
                                catName.id = data[key].category_name + "hidden";
                                newForm.appendChild(catName);

                                const catSubmit = document.createElement("input");
                                catSubmit.type= "submit"
                                catSubmit.value = data[key].category_name
                                catSubmit.className = "cat-button"
                                newForm.appendChild(catSubmit);

                                const expandButton = document.createElement("button");
                                expandButton.setAttribute('onclick', 'get_sub_category(\'' + data[key].category_name + '\');swap(\'' + data[key].category_name + '\')');
                                expandButton.className = "btn"
                                expandButton.type = "button"
                                expandButton.setAttribute("data-toggle", "collapse")
                                expandButton.setAttribute("data-target", "#" + data[key].category_name)
                                expandButton.innerHTML = "+"
                                expandButton.id = data[key].category_name + " expand";
                                newDiv.append(expandButton)

                                const newDiv2 = document.createElement("div")
                                newDiv2.className = "collapse"
                                newDiv2.id = data[key].category_name
                                newDiv2.style.margin = "0 0 0 30px";


                                subCatDiv.appendChild(newDiv);
                                subCatDiv.appendChild(newDiv2);
                              }
                        }
                    })
                })
            }
        }
    </script>
{% endblock %}

app/templates/buyer/prodByCat.html
{% extends 'base.html' %}

{% block style %}
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/productbycat.css') }}">
{% endblock %}

{% block navbar_content %}
    <li class="nav-item active">
        <a class="nav-link" href="{{ url_for("buyer.index") }}">Home <span class="sr-only">(current)</span></a>
    </li>
{% endblock %}

{% block main_content %}
    <div class="page-container">
        <div class="cat-header">
            <h1>Category: {{ category }}</h1>
        </div>
        <div class="product-container">
        {% for i in result %}
            <form method="POST" action="{{ url_for("api.to_product") }}">
                <div class="single-product-container">
                    <div class="product-name-container">
                        <button type="submit">{{ i.product_name }}</button>
                    </div>
                    <!--<div class="product-inner-container">
                        <button type="submit">Category: {{ i.category }}</button>
                    </div>-->
                    <div class="product-inner-container">
                        <button type="submit">Title: {{ i.product_title }}</button>
                    </div>
                    <div class="product-inner-container">
                        <button type="submit">Seller: {{ i.business_name }}</button>
                    </div>
                    <div class="product-inner-container">
                        <button type="submit">Contact: {{ i.seller_email }}</button>
                    </div>
                    <div class="product-inner-container">
                        <button type="submit">Description: {{ i.product_description }}</button>
                    </div>
                    <div class="product-inner-container">
                        <button type="submit">Quantity Available: {{ i.quantity }}</button>
                    </div>
                    <div class="product-inner-container">
                        <button type="submit">Unit Price: ${{ i.product_price }}</button>
                    </div>
                    <div>
                        <input type="hidden" name="listing_id" id="listing_id" value="{{ i.listing_id }}">
                    </div>
                    <div>
                        <input type="hidden" name="business_name" id="business_name" value="{{ i.business_name }}">
                    </div>
                </div>
            </form>
        {% endfor %}
        </div>
    </div>
{% endblock %}

app/templates/buyer/search.html
{% extends 'base.html' %}

{% block style %}
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/buyer.css') }}">
{% endblock %}

{% block navbar_content %}
    <li class="nav-item active">
        <a class="nav-link" href="{{ url_for("buyer.index") }}">Home <span class="sr-only">(current)</span></a>
    </li>
{% endblock %}

{% block main_content %}
    <div class="container">
        <div class="search-container">
            <form class="form-search" method="post" action="{{ url_for("buyer.search") }}">
                <input class="form-control input-search" type="search" placeholder="Search for Product" aria-label="Search" name="search" id="search" value="{{ search }}">
                <a onclick="changeCollapsible()" class="btn btn-light" data-toggle="collapse" href="#moreOptions" role="button" aria-expanded="false" id="searchOption">Show More Filter Options</a>
                <div class="collapse option-container text-center" id="moreOptions">
                    <label for="minCostRange" class="form-label">Minimum Cost</label>
                    <input type="range" class="form-range" id="minCostRange" name="minCostRange" min="0" max="1000000" step="1000" value="0">
                    <label for="maxCostRange" class="form-label">Maximum Cost</label>
                    <input type="range" class="form-range" id="maxCostRange" name="maxCostRange" min="0" max="1000000" step="1000" value="1000000">
                    <div class="range-container">
                        <span id="minValue">0</span>
                        <span>-</span>
                        <span id="maxValue">0</span>
                    </div>
                </div>
                <button class="btn btn-light my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>
        <div class="product-container">
            {% for i in results %}
                <div class="individual-product-container">
                    <form method="POST" action="{{ url_for("api.to_product") }}">
                        <div class="product-name-container">
                            <button class="h4" type="submit">{{ i.product_name }}</button>
                        </div>
                        <div class="product-inner-container">
                            <button type="submit">Category: {{ i.category }}</button>
                        </div>
                        <div class="product-inner-container">
                            <button type="submit">Title: {{ i.product_title }}</button>
                        </div>
                        <div class="product-inner-container">
                            <button type="submit">Seller: {{ i.business_name }}</button>
                        </div>
                        <div class="product-inner-container">
                            <button type="submit">Contact: {{ i.seller_email }}</button>
                        </div>
                        <div class="product-inner-container">
                            <button type="submit">Description: {{ i.product_description }}</button>
                        </div>
                        <div class="product-inner-container">
                            <button type="submit">Quantity Available: {{ i.quantity }}</button>
                        </div>
                        <div class="product-inner-container">
                            <button type="submit">Unit Price: {{ i.product_price }}</button>
                        </div>
                        <div>
                            <input type="hidden" name="listing_id" id="listing_id" value="{{ i.listing_id }}">
                        </div>
                        <div>
                            <input type="hidden" name="business_name" id="business_name" value="{{ i.business_name }}">
                        </div>
                    </form>
                </div>
            {% endfor %}
        </div>
    </div>
    <script>
        let collapsible = document.getElementById("searchOption");
        let min_slider = document.getElementById("minCostRange");
        let max_slider = document.getElementById("maxCostRange");
        let min_val = document.getElementById("minValue");
        let max_val = document.getElementById("maxValue");
        let option = document.getElementById("moreOptions");

        function changeCollapsible() {
            if (collapsible.innerHTML === "Show More Filter Options") {
                collapsible.innerHTML = "Show Less Filter Options";
                option.style.display = "flex";
            } else {
                collapsible.innerHTML = "Show More Filter Options";
                option.style.display = "none";
            }
        }

        function updateRange() {
            if (min_slider.value > max_slider.value) {
                max_slider.value = min_slider.value;
            }

            min_val.textContent = min_slider.value;
            max_val.textContent = max_slider.value;
        }

        min_slider.addEventListener('input', function () {
            updateRange();
        });

        max_slider.addEventListener('input', function () {
            updateRange();
        });

        window.addEventListener('load', updateRange);
    </script>
{% endblock %}

app/templates/buyer/setting.html
{% extends 'base.html' %}

{% block style %}
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/setting.css') }}">
{% endblock %}

{% block navbar_content %}
    <li class="nav-item active">
        <a class="nav-link" href="{{ url_for("buyer.index") }}">Home <span class="sr-only">(current)</span></a>
    </li>
    <li class="nav-item active">
        <a class="nav-link" href="{{ url_for("buyer.get_setting") }}">Setting <span class="sr-only">(current)</span></a>
    </li>
    <li class="nav-item active">
        <form action="{{ url_for('api.logout') }}" method="POST">
            <button type="submit" class="nav-link btn btn-link active" style="font-size: 17.6px;">Logout</button>
        </form>
    </li>
{% endblock %}

{% block main_content %}
    <div class="container">
            <form method="post" action="{{ url_for("buyer.update_email") }}">
                <div class="email-container">
                    <h4>Changes to Email Must Be Approved By HelpDesk</h4>
                    <label for="email">Current Email</label>
                    <input id="email" name="email" value="{{ result[0].email }}" readonly>
                    <label for="new_email">New Email</label>
                    <input type="email" id="new_email" name="new_email" placeholder="Enter New Email" required>
                    <input class="submit" type="submit" value="Create Ticket">
                    <div class="response">
                        {% if ticket_created == 'true'%}
                            Ticket Successfully Created
                        {% endif %}
                    </div>
                </div>
            </form>
            <form method="post" action="{{ url_for("buyer.update_setting") }}">
                <div class="other-setting-container">
                    <h4>Change Settings</h4>
                    <label for="password">New Password</label>
                    <input id="password" name="password" type="password">

                    <label for="conf_password">Confirm Password</label>
                    <input id="conf_password" name="conf_password" type="password">
                    
                    <label for="business_name">Business Name</label>
                    <input id="business_name" name="business_name" value="{{ result[0].business_name }}">

                    <label for="credit_num">Credit Card Number</label>
                    <input id="credit_num" name="credit_num" value="{{ result[0].credit_card_num }}">

                    <label for="expire_date">Credit Card Expiration Date</label>
                    <input id="expire_date" name="expire_date" value="{{ result[0].expire_month }}/{{ result[0].expire_year }}">

                    <label for="security_code">Security Number</label>
                    <input id="security_code" name="security_code" value="{{ result[0].security_code }}">

                    <label for="zip_code">Zip Code</label>
                    <input id="zip_code" name="zip_code" value="{{ result[0].zipcode }}">

                    <label for="street_name">Street Name</label>
                    <input id="street_name" name="street_name" value="{{ result[0].street_name }}">
                    
                    <label for="street_num">Street Number</label>
                    <input id="street_num" name="street_num" value="{{ result[0].street_num }}">

                    <input id="address_id" name="address_id" type="hidden" value="{{ result[0].address_id }}">
                    <input type="submit" value="Update Settings">
                </div>
            </form>
    </div>
{% endblock %}