app/helpdesk/__init__.py
from flask import Blueprint

bp = Blueprint('helpdesk', __name__)

from app.helpdesk import routes

app/helpdesk/routes.py
from app.helpdesk import bp
from app import get_db
from flask import render_template, request, session, redirect, url_for
import sqlite3

@bp.route('/')
def index():
    db = get_db()
    db.row_factory = sqlite3.Row
    cursor = db.cursor()

    # status 0 is incomplete, 1 is complete
    cursor.execute("SELECT * FROM requests WHERE request_status = 0")
    rows = cursor.fetchall()
    db.close()

    return render_template('helpdesk/index.html', result=rows)

@bp.route('/claim')
def claim():
    db = get_db()
    db.row_factory = sqlite3.Row
    cursor = db.cursor()

    # status 0 is incomplete, 1 is complete
    cursor.execute("SELECT * FROM requests WHERE (request_status = 0) & (helpdesk_staff_email = 'helpdeskteam@nittybiz.com')")
    rows = cursor.fetchall()
    db.close()

    return render_template('helpdesk/claim.html', result=rows)

@bp.route('/claim_request', methods=['POST'])
def claim_request():
    request_id = request.form.get('request_id')
    user = session.get('user')

    db = get_db()
    cursor = db.cursor()

    cursor.execute("UPDATE requests SET helpdesk_staff_email = ? where request_id = ?", (user, request_id))
    db.commit()
    db.close()
    return redirect(url_for("helpdesk.claim"))

@bp.route('/view')
def view():
    user = session.get('user')
    db = get_db()
    db.row_factory = sqlite3.Row
    cursor = db.cursor()

    # status 0 is incomplete, 1 is complete
    cursor.execute("SELECT * FROM requests WHERE request_status = 0 and helpdesk_staff_email = ?", (user,))
    rows = cursor.fetchall()
    db.close()

    return render_template('helpdesk/view.html', result=rows)

@bp.route('/addcategory')
def addcategory():
    return render_template('helpdesk/addcategory.html')

@bp.route('/addcatfunc', methods=['POST'])
def addcatfunc():
    cat_name = request.form.get("category_name")
    parent_name = request.form.get("parent_category_name")

    db = get_db()
    cursor = db.cursor()

    try:
        row = cursor.execute("SELECT * FROM Categories WHERE category_name = ?", (cat_name,)).fetchall()
        if len(row) == 0:
            cursor.execute("INSERT into Categories (category_name, parent_category) VALUES (?, ?)", (cat_name, parent_name))
            db.commit()
        else:
            return render_template('helpdesk/addcategory.html', ret='fail')
    except Exception as e:
        print(f"Database Error: {e}")
        return f"Error while inserting new category: {e}"
    finally:
        db.close()
    return render_template('helpdesk/addcategory.html', ret='success')

app/templates/helpdesk/addcategory.html
{% extends 'helpdesk/base.html' %}

{% block main_content %}
    <div class="addcat-container">
        <form method="post" action="{{ url_for("helpdesk.addcatfunc") }}"> <!-- Add Action here -->
            <div class="input-label">
                <label class="h1" for="category_name">Category Name</label>
                <input id="category_name" name="category_name">
            </div>
            <div class="input-label">
                <label class="h1" for="parent_category_name">Parent Category Name</label>
                <input id="parent_category_name" name="parent_category_name">
            </div>
            <div class="submit-button-container">
                <input type="submit" id="submit-change" value="Add Category">
            </div>
            {% if ret == 'success' %}
                <div class="ret">
                    Category Successfully Added
                </div>
            {% elif ret== 'fail' %}
                <div class="ret">
                    Category Already Exists
                </div>
            {% endif %}
        </form>
    </div>

{% endblock %}

app/templates/helpdesk/base.html
{% extends 'base.html' %}

{% block style %}
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/helpdesk.css') }}">
{% endblock %}

{% block navbar_content %}
    <li class="nav-item active">
        <a class="nav-link" href="{{ url_for("main.index") }}">Home <span class="sr-only">(current)</span></a>
    </li>
    <li class="nav-item dropdown active">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Actions
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{{ url_for("helpdesk.addcategory") }}">Add Category</a>
              <a class="dropdown-item" href="#">Not Implemented</a>
              <a class="dropdown-item" href="#">Not Implemented</a>
        </div>
    </li>
    <li class="nav-item active">
        <a class="nav-link" href="{{ url_for("helpdesk.index") }}">Complete Request
            <span class="sr-only">(current)</span></a>
    </li>
    <li class="nav-item active">
        <a class="nav-link" href="{{ url_for("helpdesk.claim") }}">Claim Request
            <span class="sr-only">(current)</span></a>
    </li>
    <li class="nav-item active">
        <a class="nav-link" href="{{ url_for("helpdesk.view") }}">View Your Requests
            <span class="sr-only">(current)</span></a>
    </li>
    <li class="nav-item active">
        <a class="nav-link" href="{{ url_for("api.logout") }}">Logout</a>
    </li>
{% endblock %}

app/templates/helpdesk/claim.html
{% extends 'helpdesk/base.html' %}

{% block main_content %}
    <div class="container">
        <form method="post" action="{{ url_for("helpdesk.claim_request") }}">
            <div class="submit-container">
                <div class="input-label">
                    <label for="request_id">Request ID to Claim</label>
                    <input id="request_id" name="request_id">
                </div>
                <div class="submit-button-container">
                    <input type="submit" id="submit-change" value="Claim Request">
                </div>
            </div>
        </form>

        <div class="table-container">
            <div class="card-body">
                <h2 class="card-title">Helpdesk Requests</h2>
                <table class="table">
                    <tr>
                        <th scope="col"> Request ID</th>
                        <th scope="col"> Sender Email</th>
                        <th scope="col"> Helpdesk Staff Email</th>
                        <th scope="col"> Request Type</th>
                        <th scope="col"> Description</th>
                        <th scope="col"> Status</th>
                    </tr>
                    <tbody>
                    {% for request_id, sender_email, helpdesk_staff_email, request_type, request_desc, request_status in result %}
                        <tr>
                            <td> {{ request_id }}</td>
                            <td> {{ sender_email }} </td>
                            <td> {{ helpdesk_staff_email }} </td>
                            <td> {{ request_type }} </td>
                            <td> {{ request_desc }} </td>
                            <td> {{ request_status }} </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

app/templates/helpdesk/index.html
{% extends 'helpdesk/base.html' %}

{% block main_content %}
    <div class="container">
        <form method="post" action="{{ url_for("api.complete_requests") }}">
            <div class="submit-container">
                <div class="input-label">
                    <label for="request_id">Request ID to Complete</label>
                    <input id="request_id" name="request_id">
                </div>
                <div class="submit-button-container">
                    <input type="submit" id="submit-change" value="Mark Complete">
                </div>
            </div>
        </form>

        <div class="table-container">
            <div class="card-body">
                <h2 class="card-title">Helpdesk Requests</h2>
                <table class="table">
                    <tr>
                        <th scope="col"> Request ID</th>
                        <th scope="col"> Sender Email</th>
                        <th scope="col"> Helpdesk Staff Email</th>
                        <th scope="col"> Request Type</th>
                        <th scope="col"> Description</th>
                        <th scope="col"> Status</th>
                    </tr>
                    <tbody>
                    {% for request_id, sender_email, helpdesk_staff_email, request_type, request_desc, request_status in result %}
                        <tr>
                            <td> {{ request_id }}</td>
                            <td> {{ sender_email }} </td>
                            <td> {{ helpdesk_staff_email }} </td>
                            <td> {{ request_type }} </td>
                            <td> {{ request_desc }} </td>
                            <td> {{ request_status }} </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

app/templates/helpdesk/view.html
{% extends 'helpdesk/base.html' %}

{% block main_content %}
        <div class="table-container">
            <div class="card-body">
                <h2 class="card-title">Helpdesk Requests</h2>
                <table class="table">
                    <tr>
                        <th scope="col"> Request ID</th>
                        <th scope="col"> Sender Email</th>
                        <th scope="col"> Helpdesk Staff Email</th>
                        <th scope="col"> Request Type</th>
                        <th scope="col"> Description</th>
                        <th scope="col"> Status</th>
                    </tr>
                    <tbody>
                    {% for request_id, sender_email, helpdesk_staff_email, request_type, request_desc, request_status in result %}
                        <tr>
                            <td> {{ request_id }}</td>
                            <td> {{ sender_email }} </td>
                            <td> {{ helpdesk_staff_email }} </td>
                            <td> {{ request_type }} </td>
                            <td> {{ request_desc }} </td>
                            <td> {{ request_status }} </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}